apiVersion: apps/v1
kind: Deployment
metadata:
  name: webrtc-video-conferencing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webrtc-video-conferencing
  template:
    metadata:
      labels:
        app: webrtc-video-conferencing
    spec:
      containers:
      - name: webrtc-video-conferencing
        image: samithaagrapala/webrtc-video-conferencing:latest
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: webrtc-video-conferencing-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: webrtc-video-conferencing